name: Replace Kindle Readme

on:
  schedule:
    - cron: "59 23 * * *"
  push:
    branches:
      - main
    paths:
      - ./kindle/kindle.py
      - ./kindle/requirements.txt
  workflow_dispatch:

env:
  # change env here
  GITHUB_NAME: shaonianche
  GITHUB_EMAIL: duanfei.job@gmail.com

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      # from pdm
      - name: Set Variables
        id: set_variables
        run: |
          echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
          echo "::set-output name=PIP_CACHE::$(pip cache dir)"
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./kindle/requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Replace README MAKE KINDLE INFO
        run: |
          python kindle/kindle.py '${{ secrets.KINDLE_COOKIE}}' --is-cn # delete --is-cn if you are using com

      - name: Push new README
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.G_TOKEN }}
          commit-message: "Replace README"
          files: README.md
          rebase: "true"
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}
