name: Docs lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: docs-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@main

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
